/**
 * Generates GraphQL typeDefs + default resolvers from the Prisma DMMF.
 *
 * Output:
 *   src/schema/generated/typeDefs.generated.ts  — SDL types, enums, default Query/Mutation root, inputs
 *   src/schema/generated/resolvers.generated.ts — default CRUD root resolvers + relation field resolvers
 *
 * Custom ops live in:
 *   src/schema/custom/typeDefs.custom.ts  (use `extend type Query` / `extend type Mutation`)
 *   src/schema/custom/resolvers.custom.ts
 *
 * Both layers are merged in src/schema/typeDefs.ts and src/schema/resolvers.ts.
 */

import { Prisma } from '@prisma/client'
import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outDir = join(__dirname, '..', 'src', 'schema', 'generated')
const overridesPath = join(__dirname, '..', 'src', 'schema', 'custom', 'overrides.json')
mkdirSync(outDir, { recursive: true })

interface Overrides {
  queries: string[]
  mutations: string[]
}
const overrides: Overrides = existsSync(overridesPath)
  ? JSON.parse(readFileSync(overridesPath, 'utf8'))
  : { queries: [], mutations: [] }
const overriddenQueries = new Set(overrides.queries ?? [])
const overriddenMutations = new Set(overrides.mutations ?? [])

const datamodel = Prisma.dmmf.datamodel
const models = datamodel.models
const enums = datamodel.enums

const lower = (s: string) => s.charAt(0).toLowerCase() + s.slice(1)

// Map Prisma scalar → GraphQL scalar
function gqlScalar(prismaType: string): string {
  switch (prismaType) {
    case 'String':
      return 'String'
    case 'Int':
      return 'Int'
    case 'Float':
      return 'Float'
    case 'Boolean':
      return 'Boolean'
    case 'DateTime':
      return 'String' // ISO string
    case 'BigInt':
      return 'String'
    case 'Decimal':
      return 'String'
    case 'Json':
      return 'JSON'
    default:
      return prismaType // enums
  }
}

function gqlType(field: Prisma.DMMF.Field): string {
  // Use GraphQL's ID scalar for primary keys
  if (field.isId) return 'ID!'
  const base =
    field.kind === 'enum' || field.kind === 'object' ? field.type : gqlScalar(field.type)
  if (field.isList) return `[${base}!]!`
  return field.isRequired ? `${base}!` : base
}

// A scalar field that auto-generates: skip from create input
function isAutoGenerated(field: Prisma.DMMF.Field): boolean {
  if (field.isUpdatedAt) return true
  if (field.hasDefaultValue) {
    const def = field.default as { name?: string } | string | number | boolean | undefined
    if (typeof def === 'object' && def?.name) {
      // function defaults like cuid(), uuid(), now(), autoincrement()
      return ['cuid', 'uuid', 'now', 'autoincrement', 'dbgenerated'].includes(def.name)
    }
    // For static defaults (e.g., `false`, `READER`), allow caller to override but make optional in input
    return false
  }
  return false
}

function createInputField(field: Prisma.DMMF.Field): string | null {
  if (field.kind === 'object') return null // skip relation objects; we use scalar FKs
  if (isAutoGenerated(field)) return null

  const type =
    field.kind === 'enum' ? field.type : gqlScalar(field.type)
  const required = field.isRequired && !field.hasDefaultValue ? '!' : ''
  const listMark = field.isList ? `[${type}!]` : type
  return `    ${field.name}: ${listMark}${required}`
}

function updateInputField(field: Prisma.DMMF.Field): string | null {
  if (field.kind === 'object') return null
  if (field.isId) return null
  if (field.isUpdatedAt) return null
  // Skip auto-managed timestamp fields
  if (field.name === 'createdAt' || field.name === 'updatedAt') return null
  // All fields optional in update
  const type =
    field.kind === 'enum' ? field.type : gqlScalar(field.type)
  const listMark = field.isList ? `[${type}!]` : type
  return `    ${field.name}: ${listMark}`
}

// ---------- typeDefs ----------

const enumDefs = enums
  .map(
    (e) =>
      `enum ${e.name} {\n${e.values.map((v) => `  ${v.name}`).join('\n')}\n}`
  )
  .join('\n\n')

const typeDefs = models
  .map((m) => {
    const fields = m.fields
      .map((f) => `    ${f.name}: ${gqlType(f)}`)
      .join('\n')
    return `  type ${m.name} {\n${fields}\n  }`
  })
  .join('\n\n')

const createInputs = models
  .map((m) => {
    const fields = m.fields
      .map(createInputField)
      .filter((f): f is string => f !== null)
      .join('\n')
    return `  input ${m.name}CreateInput {\n${fields}\n  }`
  })
  .join('\n\n')

const updateInputs = models
  .map((m) => {
    const fields = m.fields
      .map(updateInputField)
      .filter((f): f is string => f !== null)
      .join('\n')
    return `  input ${m.name}UpdateInput {\n${fields}\n  }`
  })
  .join('\n\n')

const queryRoot = models
  .map((m) => {
    const l = lower(m.name)
    const single = overriddenQueries.has(l) ? '' : `    ${l}(id: ID!): ${m.name}\n`
    const list = overriddenQueries.has(`${l}s`) ? '' : `    ${l}s: [${m.name}!]!\n`
    const count = overriddenQueries.has(`${l}sCount`) ? '' : `    ${l}sCount: Int!`
    return `${single}${list}${count}`
  })
  .filter((s) => s.trim().length > 0)
  .join('\n')

const mutationRoot = models
  .map((m) => {
    const lines: string[] = []
    if (!overriddenMutations.has(`create${m.name}`)) {
      lines.push(`    create${m.name}(input: ${m.name}CreateInput!): ${m.name}!`)
    }
    if (!overriddenMutations.has(`update${m.name}`)) {
      lines.push(`    update${m.name}(id: ID!, input: ${m.name}UpdateInput!): ${m.name}!`)
    }
    if (!overriddenMutations.has(`delete${m.name}`)) {
      lines.push(`    delete${m.name}(id: ID!): ${m.name}!`)
    }
    return lines.join('\n')
  })
  .filter((s) => s.length > 0)
  .join('\n')

const sdl = `# Auto-generated SDL — DO NOT EDIT
# Custom queries/mutations live in src/schema/custom/typeDefs.custom.ts (use extend type)

scalar JSON

${enumDefs}

${typeDefs}

${createInputs}

${updateInputs}

  type Query {
${queryRoot}
  }

  type Mutation {
${mutationRoot}
  }
`

writeFileSync(
  join(outDir, 'typeDefs.generated.ts'),
  `// Auto-generated — DO NOT EDIT
export const generatedTypeDefs = /* GraphQL */ \`
${sdl}
\`
`
)
console.log('Generated typeDefs.generated.ts')

// ---------- resolvers ----------

// For each model, build relation field resolvers using prisma.<model>.findUnique({where:{id}}).<relation>()
// + transform create/update inputs (FK scalar → connect)

function getScalarFKs(field: Prisma.DMMF.Field, model: Prisma.DMMF.Model): string[] {
  // For object relation field, return the FK scalar field names
  if (field.kind !== 'object') return []
  return [...(field.relationFromFields ?? [])]
}

const relationResolvers = models
  .map((m) => {
    const objFields = m.fields.filter((f) => f.kind === 'object')
    if (objFields.length === 0) return ''
    const l = lower(m.name)
    const fns = objFields
      .map((f) => {
        return `    ${f.name}: (parent: { id: string }) =>\n      prisma.${l}.findUnique({ where: { id: parent.id } }).${f.name}(),`
      })
      .join('\n')
    return `  ${m.name}: {\n${fns}\n  },`
  })
  .filter(Boolean)
  .join('\n')

// Helper: transform GraphQL input → Prisma create/update input
// FK scalars (authorId) → author: { connect: { id } }
// Build mapping: for each model, list of {fkField: 'authorId', relationField: 'author'}
function fkMap(model: Prisma.DMMF.Model): Array<{ fk: string; relation: string }> {
  const out: Array<{ fk: string; relation: string }> = []
  for (const f of model.fields) {
    if (f.kind === 'object' && f.relationFromFields && f.relationFromFields.length > 0) {
      // single-column FK only; composite FKs are skipped (advanced case)
      if (f.relationFromFields.length === 1) {
        out.push({ fk: f.relationFromFields[0], relation: f.name })
      }
    }
  }
  return out
}

const transformBlock = models
  .map((m) => {
    const fks = fkMap(m)
    if (fks.length === 0) {
      return `function transform${m.name}Input(input: Record<string, unknown>): Record<string, unknown> {
  return input
}`
    }
    const lines = fks
      .map(
        (x) =>
          `  if (typeof rest.${x.fk} === 'string') { (out as Record<string, unknown>).${x.relation} = { connect: { id: rest.${x.fk} } }; delete (out as Record<string, unknown>).${x.fk} }`
      )
      .join('\n')
    return `function transform${m.name}Input(input: Record<string, unknown>): Record<string, unknown> {
  const rest: Record<string, unknown> = { ...input }
  const out: Record<string, unknown> = { ...input }
${lines}
  return out
}`
  })
  .join('\n\n')

const mutationResolvers = models
  .map((m) => {
    const l = lower(m.name)
    const lines: string[] = []
    if (!overriddenMutations.has(`create${m.name}`)) {
      lines.push(
        `    create${m.name}: (_: unknown, args: { input: Record<string, unknown> }) =>\n      prisma.${l}.create({ data: transform${m.name}Input(args.input) as never }),`
      )
    }
    if (!overriddenMutations.has(`update${m.name}`)) {
      lines.push(
        `    update${m.name}: (_: unknown, args: { id: string; input: Record<string, unknown> }) =>\n      prisma.${l}.update({ where: { id: args.id }, data: transform${m.name}Input(args.input) as never }),`
      )
    }
    if (!overriddenMutations.has(`delete${m.name}`)) {
      lines.push(
        `    delete${m.name}: (_: unknown, args: { id: string }) =>\n      prisma.${l}.delete({ where: { id: args.id } }),`
      )
    }
    return lines.join('\n')
  })
  .filter((s) => s.length > 0)
  .join('\n')

// If the model has createdAt, sort list queries by newest first.
const queryResolvers = models
  .map((m) => {
    const l = lower(m.name)
    const hasCreatedAt = m.fields.some((f) => f.name === 'createdAt')
    const orderBy = hasCreatedAt ? `orderBy: { createdAt: 'desc' }` : ''
    const lines: string[] = []
    if (!overriddenQueries.has(l)) {
      lines.push(`    ${l}: (_: unknown, args: { id: string }) =>\n      prisma.${l}.findUnique({ where: { id: args.id } }),`)
    }
    if (!overriddenQueries.has(`${l}s`)) {
      lines.push(`    ${l}s: () =>\n      prisma.${l}.findMany({ ${orderBy} }),`)
    }
    if (!overriddenQueries.has(`${l}sCount`)) {
      lines.push(`    ${l}sCount: () =>\n      prisma.${l}.count(),`)
    }
    return lines.join('\n')
  })
  .filter((s) => s.length > 0)
  .join('\n')

// JSON scalar passthrough resolver (used only if any model has a Json field; harmless if not)
const hasJsonField = models.some((m) =>
  m.fields.some((f) => f.kind === 'scalar' && f.type === 'Json')
)
const jsonScalarResolver = hasJsonField
  ? `  JSON: {
    __serialize: (v: unknown) => v,
    __parseValue: (v: unknown) => v,
    __parseLiteral: (ast: { value: unknown }) => ast.value,
  },`
  : ''

writeFileSync(
  join(outDir, 'resolvers.generated.ts'),
  `// Auto-generated — DO NOT EDIT
import { prisma } from '@mock/db'

${transformBlock}

export const generatedResolvers = {
  Query: {
${queryResolvers}
  },
  Mutation: {
${mutationResolvers}
  },
${relationResolvers}
${jsonScalarResolver}
}
`
)
console.log('Generated resolvers.generated.ts')
console.log(`Done: ${models.length} models, ${enums.length} enums`)
